<?php

namespace Dwm\TchatBundle\Repository;

/**
 * Message7Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Message7Repository extends \Doctrine\ORM\EntityRepository
{
}
